### ISSUE TITLE
HGNC.FAMILY:1212 gone

### ISSUE THREAD

**Issue by cbizon** [TranslatorIIPrototypes/robo-commons#10]
The old graph had an HGNC gene family https://www.genenames.org/data/genegroup/#!/group/1212

The node-normalizer recognizes it, but it's no longer int the new KG.

**Comment by cbizon** [comment]
Once this is resolved, remember to turn on the associated tests in Answer Coalesence that are failing b/c of the missing gene families

**Comment by YaphetKG** [comment]
Hi @cbizon, @PhillipsOwen  has turned the answer coalesence back on and while running that he was detecting some nodes that were not normalized. I think running `MATCH (c:named_thing) where labels(c)=['named_thing'] return collect(c.id)`  against robokopdb2.renci.org:7474 would give those nodes. But I think this issue is now ok.
